version: "3"
services:
    django:
        container_name: django
        image: mpttexport:latest
        build: .
        stdin_open: true
        tty: true
        env_file:
            - .django.env
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        container_name: mpptexport_db
        image: bitnami/postgresql:11.3.0
        env_file:
            - .db.env
        volumes:
            - dbdata:/bitnami/postgresql
        ports:
            - "5432:5432"
volumes:
    dbdata:
