# Generated by Django 3.1.1 on 2020-09-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeyTree',
            new_name='Key',
        ),
    ]
